# Generated by https://smithery.ai. See: https://smithery.ai/docs/config#dockerfile
FROM node:lts-alpine

# Install pnpm globally
RUN npm install -g pnpm

# Create app directory
WORKDIR /app

# Copy package files and lockfile
COPY package.json pnpm-lock.yaml ./

# Install dependencies
RUN pnpm install --frozen-lockfile

# Copy the rest of the project source code
COPY . .

# Build the project
RUN pnpm run build

# The MCP service runs via stdio, so no ports need to be exposed.

# Set the command to run the MCP server
CMD ["pnpm", "start"]
